# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  {% if cookiecutter.project_packages == "all" -%}
  - pathlib
  - pyprojroot
  - ipykernel
  - pandas
  - openpyxl
  {% endif -%}
  - pip
  - python={{ cookiecutter.python_version }}
  {% if cookiecutter.project_packages == "all" -%}
  - pip:
    - pyhere
  {% endif -%}